server:
  port: 8001
spring:
  application:
    name: "spring-cloud-alibaba-provider"
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111
management:
  endpoints:
    web:
      exposure:
        include: "*"