server:
  port: 8002
spring:
  application:
    name: spring-cloud-alibaba-consumer
#  profiles:
#    active: dev
logging:
  level:
    com.example.springcloudalibabaconsumernacos8002: debug
feign:
  sentinel:
    enabled: true