server:
  port: 8401 #端口
spring:
  application:
    name: sentinel-service #服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      datasource:
        sentinel-rule:
          nacos:
            server-addr: localhost:1111
            dataId: sentinel-rule
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'